### ISSUE TITLE
[v3.1.0] Android crash: TypeError: _animatableImage.default.prefetch is not a function

### ISSUE THREAD

**Issue by thanhcuong1990** [vivaxy/react-native-auto-height-image#47]
**Describe the bug**
After update from v3.0.0 to v3.1.0 this library crash when running on Android. 

**To Reproduce**
1. Codes:
```js
<AutoHeightImage
  width={Constants.deviceWidth}
  source={{ uri: image_url }}
  resizeMethod="resize"
  fallbackSource={Images.Default}
/>
```
2. react-native run-android
3. See error
TypeError: _animatableImage.default.prefetch is not a function

**Screenshots**
![Screenshot_1585932766](https://user-images.githubusercontent.com/3401929/78385558-3d62fc00-7606-11ea-8cae-c366d6952972.png)

**Comment by ngregrichardson** [comment]
@yum650350 @vivaxy

**Comment by ngregrichardson** [comment]
@thanhcuong1990 Are you displaying a remote image or a local one?

**Comment by vivaxy** [comment]
Sorry for the trouble @thanhcuong1990. Fixed in v3.1.1.

I think it's better if we can have some tests.

**Comment by thinklinux** [comment]
Thanks for the fix guys! And thanks for the package!
